export const metadata = {
  title: "熊熊熊熊熊🐻 blog",
  description: "Generated by Next.js"
};
import "../global.css";

import Head from "next/head";
import React from "react";

const siteTitle = "熊熊熊熊熊🐻";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <Head>
        <link rel='icon' href='/images/avatar.png' />
        <meta name='description' content="XNY's personal website using Next.js" />
        <meta
          property='og:image'
          content={`https://og-image.vercel.app/${encodeURI(
            siteTitle
          )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`}
        />
        <meta name='og:title' content={siteTitle} />
        <meta name='twitter:card' content='summary_large_image' />
        <title>{siteTitle}</title>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/styles/github-dark.min.css'></link>
      </Head>
      <body>
        <main className='mx-auto max-w-2xl'>{children}</main>
      </body>
    </html>
  );
}
